name = "ai-chat-api"
main = "_worker.js"
compatibility_date = "2024-01-01"

[vars]
# These will be set in the Cloudflare dashboard
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
# DEEPSEEK_API_KEY

[[routes]]
pattern = "somefar.com/*"
zone_id = "2c715b4cf31c01fe44dce3c18a075528" # You'll need to add your Cloudflare zone ID here 